[build]
  command = "yarn build"
  functions = "src/lambda/"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/blog/:splat"


# COMMENT: This a rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
